version: '3.5'

networks:
  net:
    driver: overlay
    attachable: true

services:
  frontend:
    build:
      dockerfile: Dockerfile.develop
    image: ghcr.io/alium-finance/alium-frontend:develop
    ports:
      - 3020:3000
