version: '3.5'

networks:
  net:
    driver: overlay
    attachable: true

services:
  frontend:
    image: ghcr.io/alium-finance/alium-frontend:${VERSION}
    build:
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
