version: '3.5'

networks:
  net:
    driver: overlay
    attachable: true

services:
  frontend:
    build:
      dockerfile: Dockerfile.master
    image: ghcr.io/alium-finance/alium-frontend:master
    deploy:
      replicas: 2
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 3000:3000
