name: prod

on: workflow_dispatch 

env:
  VERSION: master
  IMAGE_ID: ghcr.io/alium-finance/alium-frontend
jobs:
  build:
    if: github.ref == 'refs/heads/master'  
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: |
          docker pull $IMAGE_ID:$VERSION
          docker build -f Dockerfile.prod . -t build --cache-from $IMAGE_ID:$VERSION
      - name: Push image
        run: |
          docker tag build $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  deploy_prod:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: [self-hosted, prod]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker stack deploy --compose-file docker-compose.yml alium --with-registry-auth
      - run: docker system prune -f
