name: stage

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

env:
  VERSION: stage
  IMAGE_ID: ghcr.io/alium-finance/alium-frontend
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: |
          docker pull $IMAGE_ID:$VERSION || true
          docker build -f Dockerfile.master . -t build --cache-from $IMAGE_ID:$VERSION
      - name: Push image
        run: |
          docker tag build $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  deploy:
    needs: build
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker stack deploy --compose-file docker-compose.stage.yml alium-frontend-stage --with-registry-auth
      - run: docker system prune -f
